version: '3.8'

services:
  mysql:
    image: mysql:8.0.28
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 3s
      retries: 5
    environment:
      - MYSQL_DATABASE=interview
      - MYSQL_ROOT_PASSWORD=#Mudar123
      - MYSQL_USER=BRomano
      - MYSQL_PASSWORD=#Mudar123
      - ST_MONITOR_MYSQL_DB_USER="spm-user"
      - ST_MONITOR_MYSQL_DB_PASSWORD="spm-password"
    expose:
      - 3306
    ports:
      - 3306
  migration:
    build: interview
    restart: on-failure
    command: flask db upgrade --directory interview/migrations
    environment:
      - FLASK_APP=interview:create_app('DevConfig')
      - DATABASE_URL=mysql://BRomano:#Mudar123@mysql:3306/interview
    depends_on:
      - mysql
  interview:
    build: interview
    command: gunicorn --workers 2 --bind 0.0.0.0:5000 "interview:create_app('DevConfig')" --max-requests 10000 --timeout 5 --keep-alive 5 --log-level info
    restart: always
    ports:
      - 5000
    environment:
      - APP_NAME="interview"
      - DEBUG=True
      - APP_LONG_NAME="Interview Test"
      - SECRET_KEY=brunoromano
      - DATABASE_URL=mysql://BRomano:#Mudar123@mysql:3306/interview
      - SQLALCHEMY_ECHO=False
    depends_on:
      - mysql
  proxy:
    build: front
    restart: always
    ports:
      - 80:80
    depends_on:
      - interview
  st-agent:
    image: sematext/agent:latest
    environment:
      - INFRA_TOKEN=c3644c5c-7306-49c6-b448-488daa8d3769
      - SERVER_BASE_URL=https://spm-receiver.sematext.com
      - LOGS_RECEIVER_URL=https://logsene-receiver.sematext.com
      - EVENT_RECEIVER_URL=https://event-receiver.sematext.com
      - COMMAND_SERVER_URL=https://command.sematext.com
    cap_add:
      - SYS_ADMIN
    restart: always
    volumes:
      - /:/hostfs:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /var/run/:/var/run
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys:/host/sys:ro
      - /dev:/hostfs/dev:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
