version: '3'
services:
  mysql:
    image: mysql:8.0.28
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 3s
      retries: 5
    environment:
      - MYSQL_DATABASE=interview
      - MYSQL_ROOT_PASSWORD=#Mudar123
      - MYSQL_USER=BRomano
      - MYSQL_PASSWORD=#Mudar123
    expose:
      - 3306
    ports:
      - 3306
  migration:
    build: interview
    command: flask db upgrade --directory interview/migrations
    environment:
      - FLASK_APP=interview:create_app('DevConfig')
      - DATABASE_URL=mysql://BRomano:#Mudar123@mysql:3306/interview
    depends_on:
      - mysql
  interview:
    build: interview
    command: gunicorn --workers 8 --bind 0.0.0.0:5000 "interview:create_app('DevConfig')" --max-requests 10000 --timeout 5 --keep-alive 5 --log-level info
    restart: always
    ports:
      - 5000
    environment:
      - APP_NAME="interview"
      - DEBUG=True
      - APP_LONG_NAME="Interview Test"
      - SECRET_KEY=brunoromano
      - DATABASE_URL=mysql://BRomano:#Mudar123@mysql:3306/interview
      - SQLALCHEMY_ECHO=False
    depends_on:
      - migration
  proxy:
    build: front
    restart: always
    ports:
      - 80:80
    depends_on:
      - interview
